#include <stdio.h>
#include <stdint.h>
#include "hardware.h"

#define MSB 0x8000
#define ISZERO(x) (x == 0) ? 1 : 0
#define ISSIGN(x) ((MSB & x) == MSB) ? 1 : 0

/**********************************************************
*   iscarry()- determine if carry is generated by addition: op1+op2+C
*     C can only have value of 1 or 0.
************************************************************/
int iscarry(uint32_t op1, uint32_t op2, uint8_t C){
if ((op2 == MAX32)&&(C == 1)) 
	return(1); // special case where op2 is at MAX32
return((op1 > (MAX32 - op2 - C))?1:0);
}


void allflagchk(uint32_t regs1, uint32_t regs2)
{
	if(ISZERO(regs1))
		regs.ZERO = 1;
	else if(!ISZERO(regs1))
		regs.ZERO = 0;
	if(ISSIGN(regs1))
		regs.SIGN = 1;
	else if(!ISSIGN(regs1))
		regs.SIGN = 0;
	if(iscarry(regs1, regs2, regs.CARRY))
		regs.CARRY = 1;
	else if(!iscarry(regs1, regs2, regs.CARRY))
		regs.CARRY = 0;
}

void nzflagchk(uint32_t regs1, uint32_t regs2)
{
	if(ISSIGN(regs1))
		regs.SIGN = 1;
	else if(!ISSIGN(regs1))
		regs.SIGN = 0;
	if(ISZERO(regs1))
		regs.ZERO = 1;
	if(!ISZERO(regs1))
		regs.ZERO = 0;
}